"""add selector_reasoning to query_runs

Revision ID: 3ee8b16c70eb
Revises: 961cff3c246b
Create Date: 2026-06-18 04:29:40.103553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee8b16c70eb'
down_revision: Union[str, None] = '961cff3c246b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_runs', sa.Column('selector_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_runs', 'selector_reasoning')
    # ### end Alembic commands ###
