"""add_token_columns

Revision ID: 973219b8de07
Revises: 94d7b234d0b9
Create Date: 2026-06-17 16:47:02.399287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973219b8de07'
down_revision: Union[str, None] = '94d7b234d0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_runs', sa.Column('tokens_input', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('query_runs', sa.Column('tokens_output', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_runs', 'tokens_output')
    op.drop_column('query_runs', 'tokens_input')
    # ### end Alembic commands ###
